### PR TITLE
Use contains function from Node prototype

### LINKED ISSUE #507: Cannot submit form containing a field called "contains" in Unpoly 3
### Bug description

If you have a form with a field called "contains" in it, Unpoly appears unable to submit it, failing with "[element].contains is not a function" where [element] varies - is normally "root" if the form is in the top layer.

### Reproduction project
https://glitch.com/edit/#!/confirmed-periodic-form

### Steps to reproduce the behavior:

The first form contains a text field called "contains".  Clicking the submit button will raise a javascript error.
The second form contains a text field called "contains2".  Clicking the submit button works fine.

### Expected behavior

Both forms should be submittable as "contains" is a valid form field identifier

### Browser version
Chrome (latest) on Windows 10

### PR DESCRIPTION
**Pull request by adam12**
When checking if in subtree where the root is `HTMLFormElement`, there is a chance that `root.contains` is actually another form element, and not the function `contains`.

To work around this, use the prototype function directly from Node.

Closes #507

### CODE REVIEW

**Comment by adam12** [comment]
I'm really not sure where I should add a test for this. Suggestions?

File: spec/unpoly/element_spec.coffee [hunk 1]
```diff
@@ -204,6 +204,13 @@ describe 'up.element', ->
       results = up.element.subtree($element[0], '.match')
       expect(results).toEqual []
 
+  describe 'up.element.isInSubtree()', ->
+    it 'can handle conflicts with forms where an input is named `contains` GH#507', ->
+      $form = $fixture('form')
+      $child = $form.affix('input[name="contains"]')
+
+      expect(up.element.isInSubtree($form[0], $child)).toBe(true)
```
Comment (adam12) [inline spec/unpoly/element_spec.coffee:212]: I had to force this to be a `Node` to be able to use the prototype, but that have might exposed another issue where elements other than a `Node` would be passed as the `root`. Thoughts?

Comment (triskweline) [reply spec/unpoly/element_spec.coffee:212]: > I had to forcefully grab the first element to be able to use the prototype function of Node

That's just because `$fixture()` returns a jQuery collection instead of a native `Element`. `$form[0]` returns the one native DOM element in that collection.

As an alternative we can use the `fixture()` and `up.element.affix()` helpers, which return an `Element`. We are eventually going to hose jQuery off the test suite.

> but that have might exposed another issue where elements other than a Node would be passed as the root

That's fine. We don't need to support arguments of any other type.

**Review by triskweline — APPROVED** [review]

**Comment by triskweline** [comment]
Thanks for the change @adam12 :heart:
